=== hafizmuhammadsufyan/APTECH_LEARNINGS/SECOND_SEMESTER/XML/tasks/DARAZ/supplier.xsd
<?xml version="1.0" encoding="UTF-8"?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="suppliers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="supplier" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="supId" type="xs:int"></xs:element>
                            <xs:element name="supName" type="xs:string"></xs:element>
                            <xs:element name="products" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="product" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="pName" type="xs:string"></xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hafizmuhammadsufyan/APTECH_LEARNINGS/SECOND_SEMESTER/tasks/DARAZ/supplier.xml
<?xml version="1.0" encoding="UTF-8"?>

<suppliers
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="supplier.xsd">

    <supplier>
        <supId>0001</supId>
        <supName>Apple</supName>
        <products>
            <product>
                <pName>Iphone</pName>
            </product>
            <product>
                <pName>Imac</pName>
            </product>
        </products>
        <products>
            <product>
                <pName>Iphone</pName>
            </product>
            <product>
                <pName>Imac</pName>
            </product>
        </products>
    </supplier>
    <supplier>
        <supId>0001</supId>
        <supName>Samsung</supName>
        <products>
            <product>
                <pName>Iphone</pName>
            </product>
            <product>
                <pName>Imac</pName>
            </product>
        </products>
        <products>
            <product>
                <pName>Iphone</pName>
            </product>
            <product>
                <pName>Imac</pName>
            </product>
        </products>
    </supplier>
</suppliers>
