=== hafizmuhammadsufyan/APTECH_LEARNINGS/SECOND_SEMESTER/XML/student.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="students">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="age" type="xs:int"></xs:element>
                            <xs:element name="marks">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="0"></xs:minInclusive>
                                        <xs:maxInclusive value="100"></xs:maxInclusive>

                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>
</xs:schema>

=== hafizmuhammadsufyan/APTECH_LEARNINGS/SECOND_SEMESTER/XML/student.xml
<?xml version="1.0" encoding="UTF-8"?>


<students
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="student.xsd">

    <student>
        <name>Ali</name>
        <age>18</age>
        <marks>95</marks>
    </student>
    <student>
        <name>Ahmed</name>
        <age>21</age>
        <marks>85</marks>
    </student>
</students>
