=== hafizmuhammadsufyan/APTECH_LEARNINGS/SECOND_SEMESTER/tasks/DARAZ/employee.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employees">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="xs:int"></xs:element>
                            <xs:element name="name" type="xs:string"></xs:element>
                            <xs:element name="age">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="18"></xs:minInclusive>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== hafizmuhammadsufyan/APTECH_LEARNINGS/SECOND_SEMESTER/tasks/DARAZ/employee.xml
<?xml version="1.0" encoding="UTF-8"?>


<employees
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="employee.xsd">

    <employee>
        <id>0012</id>
        <name>Ahmed</name>
        <age>18</age>
    </employee>
    <employee>
        <id>0012</id>
        <name>Ahmed</name>
        <age>18</age>
    </employee>
    <employee>
        <id>0012</id>
        <name>Ahmed</name>
        <age>18</age>
    </employee>
</employees>
